import { Hono } from "hono";
import { authMiddleware, requireRole } from "../../middleware/auth";
import type { Env, Variables } from "../../types";

import dashboardRoute from "./dashboard";
import campaignsRoute from "./campaigns";
import categoriesRoute from "./categories";
import pillarsRoute from "./pillars";
import donationsRoute from "./donations";
import donaturRoute from "./donatur";
import usersRoute from "./users";
import rolesRoute from "./roles";
import financeRoute from "./finance";
import ledgerRoute from "./ledger";
import coaRoute from "./coa";
import evidencesRoute from "./evidences";
import exportRoute from "./export";
import reportsRoute from "./reports";
import analyticsRoute from "./analytics";
import settingsRoute from "./settings";
import auditRoute from "./audit";
import mediaRoute from "./media";
import vendorsRoute from "./vendors";
import employeesRoute from "./employees";
import mustahiqsRoute from "./mustahiqs";
import activityReportsRoute from "./activity-reports";
import zakatTypesRoute from "./zakat-types";
import zakatDonationsRoute from "./zakat-donations";
import zakatDistributionsRoute from "./zakat-distributions";
import zakatStatsRoute from "./zakat-stats";
import qurbanRoute from "./qurban";
import qurbanSavingsRoute from "./qurban-savings";
import addressRoute from "./address";

const admin = new Hono<{ Bindings: Env; Variables: Variables }>();

admin.use("*", authMiddleware);
admin.use("*", requireRole("super_admin", "admin_finance", "admin_campaign", "program_coordinator"));

admin.route("/dashboard", dashboardRoute);
admin.route("/campaigns", campaignsRoute);
admin.route("/categories", categoriesRoute);
admin.route("/pillars", pillarsRoute);
admin.route("/donations", donationsRoute);
admin.route("/donatur", donaturRoute);
admin.route("/users", usersRoute);
admin.route("/roles", rolesRoute);
admin.route("/finance", financeRoute);
admin.route("/ledger", ledgerRoute);
admin.route("/coa", coaRoute);
admin.route("/evidences", evidencesRoute);
admin.route("/export", exportRoute);
admin.route("/reports", reportsRoute);
admin.route("/analytics", analyticsRoute);
admin.route("/settings", settingsRoute);
admin.route("/audit", auditRoute);
admin.route("/media", mediaRoute);
admin.route("/vendors", vendorsRoute);
admin.route("/employees", employeesRoute);
admin.route("/mustahiqs", mustahiqsRoute);
admin.route("/activity-reports", activityReportsRoute);
admin.route("/zakat/types", zakatTypesRoute);
admin.route("/zakat/donations", zakatDonationsRoute);
admin.route("/zakat/distributions", zakatDistributionsRoute);
admin.route("/zakat/stats", zakatStatsRoute);
admin.route("/qurban", qurbanRoute);
admin.route("/qurban/savings", qurbanSavingsRoute);
admin.route("/address", addressRoute);

export default admin;
